include ~/.config/aurora/active-kitty.conf


bold_font        auto
italic_font      auto
bold_italic_font auto

modify_font cell_height 108%

disable_ligatures cursor

cursor_shape                 block
shell_integration            no-cursor
remember_window_size  yes
initial_window_width  900
initial_window_height 600
window_padding_width  10
hide_window_decorations no

dynamic_background_opacity yes

background_blur 0

tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted

shell .
editor .
allow_remote_control socket-only
listen_on unix:$XDG_RUNTIME_DIR/kitty-{kitty_pid}
update_check_interval 0

repaint_delay 6
input_delay 1
sync_to_monitor yes

enable_audio_bell no
visual_bell_duration 0.0

mouse_hide_wait 3.0
url_style curly
open_url_with default
copy_on_select yes

scrollback_lines 10000
confirm_os_window_close 0
