# ==========================================
# Kitty Base Configuration
# ==========================================

# Static Stylix fallback
include dank-theme.conf

# Dynamic Wallust colors
include ~/.cache/wallust/kitty.conf

# Tabs
include dank-tabs.conf

# Local Kitty remote control
allow_remote_control socket-only
listen_on unix:${XDG_RUNTIME_DIR}/kitty-{kitty_pid}

# Font configuration
#font_family      Liga SFMono Nerd Font
font_family      JetBrains Mono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0
adjust_line_height 100%

# Window layout
cursor_shape                block
shell_integration           enabled
cursor_trail                0
remember_window_size  yes
initial_window_width  900
initial_window_height 600
window_padding_width  15
hide_window_decorations no
background_opacity 0.85
background_blur 48

# Tab bar
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted

# Advanced
shell .
editor .
update_check_interval 0

# Performance tuning
repaint_delay 10
input_delay 3
sync_to_monitor yes

# Bell
enable_audio_bell no
visual_bell_duration 0.0

# Mouse
mouse_hide_wait 3.0
url_style curly
open_url_with default
copy_on_select yes

# Scrollback
scrollback_lines 10000
confirm_os_window_close 0
