# ==========================================
# Wallust generated configuration
# ==========================================

[main]

# Typography
font=JetBrainsMono Nerd Font:size=11

# Layout
width=48
lines=10

horizontal-pad=22
vertical-pad=16
inner-pad=10

line-height=26
letter-spacing=0

# Icons
icons-enabled=yes
icon-theme=Papirus-Dark

# Wayland
layer=overlay
anchor=center

# Search
prompt="  󰍉  "
placeholder="Search applications..."

# ==========================================
# Dynamic Wallust Colors
# ==========================================

[colors]

background={{background}}e9

text={{foreground}}ff

prompt={{color4}}ff

placeholder={{color8}}ff

input={{foreground}}ff

match={{color4}}ff

selection={{color0}}f5

selection-text={{color7}}ff

selection-match={{color6}}ff

counter={{color8}}ff

border={{color4}}88

# ==========================================
# Border
# ==========================================

[border]

width=1
radius=16
selection-radius=10
