source-file ~/.config/tmux/theme/color.conf

# ---- Core ----
set -g status on
set -g status-justify left
set -g status-style "bg=default,fg=#cdd6f4"
set -g status-left-length 40
set -g status-right-length 60


# ---- Windows ----
set -g window-status-separator ""

# Focused window
set -g window-status-current-format "#[fg=#{@THM_BLUE},bg=default]#[fg=#{@THM_DARK_FG},bg=#{@THM_BLUE},bold] #I #W #[fg=#{@THM_BLUE},bg=default] "

# Unfocused window
set -g window-status-format "#[fg=#{@THM_MUTED},bg=default] #I #W "

# ---- Status Left ----
set -g status-left "#[fg=#{@THM_BLUE},bg=default]#[fg=#{@THM_DARK_FG},bg=#{@THM_BLUE},bold]#{?client_prefix,󰠠 ,󰤂 }#[bold,nodim]#S#[fg=#{@THM_BLUE},bg=default] "

# ---- Status Right ----
set -g status-right "#[fg=#{@THM_ACCENT},bg=default,bold]%d %B %Y, %A"

# ---- Panes ----
# These MUST use literal colours.
set -g pane-border-style "fg=#45475a"
set -g pane-active-border-style "fg=#cdd6f4"

# ---- Messages / Command Prompt ----
set -g message-style "bg=default,fg=#f9e2af,bold"
set -g message-command-style "bg=default,fg=#f9e2af"

# ---- Copy Mode ----
set -g mode-style "bg=#cdd6f4,fg=#1e1e2e"

# ---- Clock Mode ----
set -g clock-mode-colour "#cdd6f4"
set -g clock-mode-style 24

# ---- Display Panes ----
set -g display-panes-active-colour "#7aa2f7"
set -g display-panes-colour "#6c7086"

# ---- Activity ----
set -g monitor-activity on
set -g visual-activity off
