backend = "fastresize"
palette = "dark16"
check_contrast = true

[templates]

hyprland.template = "colors.lua"
hyprland.target = "~/.cache/wallust/colors.lua"

kitty.template = "kitty.conf"
kitty.target = "~/.cache/wallust/kitty.conf"
