{ lib, ... }:

let
  # CENTRAL THEME DATABASE

  themeData = import ../../lib/themes.nix;

  themeNames = builtins.attrNames themeData.themes;

  # LUA THEME GENERATOR

  themeToLua =
    themeId:
    let
      theme = themeData.themes.${themeId};
      colors = theme.colors;
      fonts = themeData.global.fonts;
      ui = themeData.global.ui;
    in
    ''


      -- ========================================================
      -- Aurora Theme
      -- ${theme.name}
      --
      -- GENERATED FILE.
      --
      -- DO NOT EDIT THIS FILE DIRECTLY.
      --
      -- Source:
      --   ~/NixOS/lib/themes.nix
      -- ========================================================

      return {
        id = "${themeId}",
        name = "${theme.name}",
        description = "${theme.description}",
        fonts = {
          interface = "${fonts.interface.name}",
          terminal = "${fonts.terminal.name}",
          emoji = "${fonts.emoji.name}",
          },
        colors = {
          background = "${colors.background}",
          backgroundDark = "${colors.backgroundDark}",

          surface = "${colors.surface}",
          surfaceHover = "${colors.surfaceHover}",
          surfaceActive = "${colors.surfaceActive}",

          border = "${colors.border}",
          borderFocus = "${colors.borderFocus}",
          separator = "${colors.separator}",

          text = "${colors.text}",
          textSecondary = "${colors.textSecondary}",
          textMuted = "${colors.textMuted}",

          accent = "${colors.accent}",
          accentHover = "${colors.accentHover}",
          accentActive = "${colors.accentActive}",
          accentMuted = "${colors.accentMuted}",
          accentForeground = "${colors.accentForeground}",

          success = "${colors.success}",
          warning = "${colors.warning}",
          error = "${colors.error}",
          info = "${colors.info}",

          terminalBlack = "${colors.terminalBlack}",
          terminalRed = "${colors.terminalRed}",
          terminalGreen = "${colors.terminalGreen}",
          terminalYellow = "${colors.terminalYellow}",
          terminalBlue = "${colors.terminalBlue}",
          terminalMagenta = "${colors.terminalMagenta}",
          terminalCyan = "${colors.terminalCyan}",
          terminalWhite = "${colors.terminalWhite}",

          terminalBrightBlack = "${colors.terminalBrightBlack}",
          terminalBrightRed = "${colors.terminalBrightRed}",
          terminalBrightGreen = "${colors.terminalBrightGreen}",
          terminalBrightYellow = "${colors.terminalBrightYellow}",
          terminalBrightBlue = "${colors.terminalBrightBlue}",
          terminalBrightMagenta = "${colors.terminalBrightMagenta}",
          terminalBrightCyan = "${colors.terminalBrightCyan}",
          terminalBrightWhite = "${colors.terminalBrightWhite}",
        },

        ui = {
          borderWidth = ${toString ui.borderWidth},

          radius = ${toString ui.radius},
          radiusSmall = ${toString ui.radiusSmall},
          radiusLarge = ${toString ui.radiusLarge},

          iconSize = ${toString ui.iconSize},

          fontSize = ${toString ui.fontSize},
          fontSizeSmall = ${toString ui.fontSizeSmall},
          fontSizeLarge = ${toString ui.fontSizeLarge},

          shadowOpacity = ${toString ui.shadowOpacity},
          shadowOpacity = ${toString ui.shadowOpacity},
          surfaceOpacity = ${toString ui.surfaceOpacity},
          windowOpacity = ${toString ui.windowOpacity},

          -- Liquid glass. Consumed by Quickshell rather than by Hyprland
          glassOpacity = ${toString ui.glassOpacity},
          glassLuminosity = ${toString ui.glassLuminosity},
          glassGradientOpacity = ${toString ui.glassGradientOpacity},
          glassGrainOpacity = ${toString ui.glassGrainOpacity},
          glassRimOpacity = ${toString ui.glassRimOpacity},

          glassSpecularOpacity = ${toString ui.glassSpecularOpacity},
          glassLensOpacity = ${toString ui.glassLensOpacity},
          glassDepthOpacity = ${toString ui.glassDepthOpacity},
          glassClarity = ${toString ui.glassClarity},

          -- These two ARE read from Lua, and by neovim specifically:
          -- ui/theme.lua dofiles this file and derives its transparency from
          -- terminalOpacity, the same value themeToKitty below writes into
          -- kitty's background_opacity. One knob, so the editor and the terminal
          -- it runs in cannot end up disagreeing about whether they are glass.
          terminalOpacity = ${toString ui.terminalOpacity},
          editorFloatBlend = ${toString ui.editorFloatBlend},

          clock = {
            hour = "${ui.clock.hour}",
            separator = "${ui.clock.separator}",
            minute = "${ui.clock.minute}",
            second = "${ui.clock.second}",
          },
        },
      }
    '';

  # QUICKSHELL JSON THEME GENERATOR

  themeToJson =
    themeId:
    builtins.toJSON {
      id = themeId;

      name = themeData.themes.${themeId}.name;

      description = themeData.themes.${themeId}.description;

      fonts = {
        interface = themeData.global.fonts.interface.name;
        terminal = themeData.global.fonts.terminal.name;
        emoji = themeData.global.fonts.emoji.name;
      };

      colors = themeData.themes.${themeId}.colors;

      ui = themeData.global.ui;
    };

  # KITTY THEME GENERATOR

  themeToKitty =
    themeId:
    let
      theme = themeData.themes.${themeId};
      colors = theme.colors;
      fonts = themeData.global.fonts;
      ui = themeData.global.ui;
    in
    ''
      # ========================================================
      # Aurora Kitty Theme
      # ${theme.name}
      #
      # GENERATED FILE.
      #
      # DO NOT EDIT THIS FILE DIRECTLY.
      #
      # Source:
      #   ~/NixOS/lib/themes.nix
      # ========================================================

      # --------------------------------------------------------
      # Typography
      # --------------------------------------------------------

      font_family ${fonts.terminal.name}

      font_size ${toString ui.fontSize}


      # --------------------------------------------------------
      # Core
      # --------------------------------------------------------

      foreground ${colors.text}
      background ${colors.background}

      cursor ${colors.accent}
      cursor_text_color ${colors.accentForeground}

      # accentForeground is a near-background tone; on accentMuted it gave
      # 1.4-2.8:1 in every theme, i.e. selected text was invisible.
      selection_foreground ${colors.text}
      selection_background ${colors.accentMuted}

      url_color ${colors.info}


      # --------------------------------------------------------
      # ANSI Colors
      # --------------------------------------------------------

      color0  ${colors.terminalBlack}
      color1  ${colors.terminalRed}
      color2  ${colors.terminalGreen}
      color3  ${colors.terminalYellow}
      color4  ${colors.terminalBlue}
      color5  ${colors.terminalMagenta}
      color6  ${colors.terminalCyan}
      color7  ${colors.terminalWhite}

      color8  ${colors.terminalBrightBlack}
      color9  ${colors.terminalBrightRed}
      color10 ${colors.terminalBrightGreen}
      color11 ${colors.terminalBrightYellow}
      color12 ${colors.terminalBrightBlue}
      color13 ${colors.terminalBrightMagenta}
      color14 ${colors.terminalBrightCyan}
      color15 ${colors.terminalBrightWhite}


      # --------------------------------------------------------
      # Tabs
      # --------------------------------------------------------

      tab_bar_background ${colors.background}

      active_tab_foreground ${colors.accentForeground}
      active_tab_background ${colors.accent}

      inactive_tab_foreground ${colors.textSecondary}
      inactive_tab_background ${colors.surface}


      # --------------------------------------------------------
      # Transparency
      # --------------------------------------------------------

      # Kitty's own opacity, deliberately NOT Hyprland's active_opacity --
      # Hyprland fades glyphs too, this fades only the background. The blur is
      # still Hyprland's; background_blur stays 0 in kitty.conf. Declared in
      # themes.nix so all 21 themes necessarily agree and switching theme can
      # never change how transparent the terminal is.
      background_opacity ${toString ui.terminalOpacity}

      # No transparent_background_colors here, on purpose. It makes cells whose
      # background matches a listed colour translucent *on top of* a window
      # background that background_opacity has already been applied to -- and the
      # default cell background IS colors.background, so it matched every cell
      # and squared the opacity. Padding is not a cell, so it kept the single
      # application: measured 0.769 padding against 0.511 cells at 0.72, which is
      # the solid frame that used to ring every window.
      #
      # The cost is that a TUI painting cells with the theme background
      # explicitly gets an opaque block. Standard kitty behaviour, and Aurora's
      # editor avoids it by setting those groups to NONE.
    '';

  # STARSHIP THEME GENERATOR

  themeToStarship =
    themeId:
    let
      theme = themeData.themes.${themeId};
      colors = theme.colors;
    in
    ''
      # ========================================================
      # Aurora Starship Theme
      # ${theme.name}
      #
      # GENERATED FILE.
      #
      # DO NOT EDIT THIS FILE DIRECTLY.
      #
      # Source:
      #   ~/NixOS/lib/themes.nix
      # ========================================================


      add_newline = false

      command_timeout = 1000

      scan_timeout = 30

      follow_symlinks = false


      palette = "aurora"


      # ========================================================
      # PROMPT
      # ========================================================

      format = """
      $directory\
      ''${custom.giturl}\
      $git_branch\
      ''${custom.git_worktree}\
      $git_status\
      $package\
      $nodejs\
      $bun\
      $c\
      $rust\
      $golang\
      $php\
      $java\
      $kotlin\
      $haskell\
      $python\
      $docker_context\
      $cmd_duration\
      $character"""


      # ========================================================
      # AURORA PALETTE
      # ========================================================

      [palettes.aurora]

      # --------------------------------------------------------
      # Main surfaces
      # --------------------------------------------------------

      bg = "${colors.background}"

      surface = "${colors.surface}"

      surface2 = "${colors.surfaceHover}"

      surface3 = "${colors.surfaceActive}"


      # --------------------------------------------------------
      # Text
      # --------------------------------------------------------

      text = "${colors.text}"

      text_soft = "${colors.textSecondary}"

      muted = "${colors.textMuted}"

      dim = "${colors.textMuted}"


      # --------------------------------------------------------
      # Primary Accent
      # --------------------------------------------------------

      purple = "${colors.accent}"

      purple_bright = "${colors.accentHover}"

      purple_soft = "${colors.accentMuted}"

      purple_dark = "${colors.border}"


      # --------------------------------------------------------
      # Cool Accents
      # --------------------------------------------------------

      blue = "${colors.terminalBlue}"

      cyan = "${colors.terminalCyan}"


      # --------------------------------------------------------
      # Status
      # --------------------------------------------------------

      green = "${colors.success}"

      yellow = "${colors.warning}"

      orange = "${colors.warning}"

      red = "${colors.error}"

      pink = "${colors.terminalMagenta}"


      # ========================================================
      # OS
      # ========================================================

      [os]

      disabled = false

      style = "bold text"

      format = "[$symbol ]($style)"


      [os.symbols]

      NixOS = ""

      Linux = "󰌽"

      Arch = "󰣇"

      Artix = "󰣇"

      Ubuntu = "󰕈"

      Fedora = "󰣛"

      Debian = "󰣚"

      Gentoo = "󰣨"

      Manjaro = ""

      Mint = "󰣭"

      SUSE = ""

      Raspbian = "󰐿"

      Alpine = ""

      Amazon = ""

      Android = ""

      CentOS = ""

      Redhat = "󱄛"

      RedHatEnterprise = "󱄛"

      Macos = ""

      Windows = "󰍲"


      # ========================================================
      # DIRECTORY
      # ========================================================

      [directory]

      style = "bold text"

      format = "[$path]($style)[$read_only]($read_only_style) "

      home_symbol = "~"

      truncation_length = 3

      truncate_to_repo = false

      truncation_symbol = "…/"

      read_only = " 󰌾"

      read_only_style = "bold red"

      # ========================================================
      # GIT REMOTE
      # ========================================================

      [custom.giturl]

      description = "Display symbol for remote Git server"

      command = """
      GIT_REMOTE=$(git remote get-url origin 2>/dev/null)

      case "$GIT_REMOTE" in
          *github*)
              echo ""
              ;;
          *gitlab*)
              echo ""
              ;;
          *bitbucket*)
              echo ""
              ;;
          *git*)
              echo ""
              ;;
          *)
              echo ""
              ;;
      esac
      """

      when = "git rev-parse --is-inside-work-tree 2>/dev/null"

      format = "[$output](bold purple)  "

      require_repo = true

      ignore_timeout = true


      # ========================================================
      # GIT BRANCH
      # ========================================================

      [git_branch]

      symbol = " "

      format = "[](purple)[ $symbol$branch ](bold bg bg:purple)[](purple) "


      # ========================================================
      # GIT WORKTREE
      # ========================================================

      [custom.git_worktree]

      description = "Show indicator when inside a Git worktree"

      command = """
      if git rev-parse --git-dir >/dev/null 2>&1; then
          common_dir=$(git rev-parse --path-format=absolute --git-common-dir 2>/dev/null)
          git_dir=$(git rev-parse --path-format=absolute --git-dir 2>/dev/null)

          if [ "$common_dir" != "$git_dir" ]; then
              echo "⛓"
          fi
      fi
      """

      when = "git rev-parse --is-inside-work-tree >/dev/null 2>&1"

      format = "[$output](bold purple) "

      style = "bold purple"

      require_repo = true

      ignore_timeout = true


      # ========================================================
      # GIT STATUS
      # ========================================================

      [git_status]

      style = "bold text"

      format = "[$untracked$staged$modified$renamed$deleted$conflicted$stashed$typechanged$ahead_behind]($style) "


      untracked = "[?](bold red)"

      staged = "[+](bold green)"

      modified = "[!](bold yellow)"

      renamed = "[»](bold blue)"

      deleted = "[-](bold red)"

      conflicted = "[✖](bold red)"

      stashed = "[≡](bold purple)"

      typechanged = "[󰜄](bold cyan)"


      ahead = "[⇡''${count}](bold cyan)"

      behind = "[⇣''${count}](bold orange)"

      diverged = "[⇕⇡''${ahead_count}⇣''${behind_count}](bold pink)"

      up_to_date = ""


      # ========================================================
      # PACKAGE
      # ========================================================

      [package]

      disabled = false

      symbol = "󰏗 "

      style = "bold purple"

      format = "[$symbol$version]($style) "


      # ========================================================
      # NODE.JS
      # ========================================================

      [nodejs]

      symbol = ""

      style = "bold green"

      format = "[$symbol( $version)]($style) "


      # ========================================================
      # BUN
      # ========================================================

      [bun]

      symbol = "🥟"

      style = "bold orange"

      format = "[$symbol( $version)]($style) "

      detect_files = [
        "bun.lock",
        "bun.lockb",
      ]


      # ========================================================
      # C
      # ========================================================

      [c]

      symbol = " "

      style = "bold blue"

      format = "[$symbol( $version)]($style) "


      # ========================================================
      # RUST
      # ========================================================

      [rust]

      symbol = ""

      style = "bold orange"

      format = "[$symbol( $version)]($style) "


      # ========================================================
      # GO
      # ========================================================

      [golang]

      symbol = ""

      style = "bold cyan"

      format = "[$symbol( $version)]($style) "

      detect_files = [
        "go.mod",
      ]


      # ========================================================
      # PHP
      # ========================================================

      [php]

      symbol = ""

      style = "bold purple"

      format = "[$symbol( $version)]($style) "


      # ========================================================
      # JAVA
      # ========================================================

      [java]

      symbol = " "

      style = "bold red"

      format = "[$symbol( $version)]($style) "


      # ========================================================
      # KOTLIN
      # ========================================================

      [kotlin]

      symbol = ""

      style = "bold pink"

      format = "[$symbol( $version)]($style) "


      # ========================================================
      # HASKELL
      # ========================================================

      [haskell]

      symbol = ""

      style = "bold purple"

      format = "[$symbol( $version)]($style) "


      # ========================================================
      # PYTHON
      # ========================================================

      [python]

      symbol = ""

      style = "bold yellow"

      format = "[$symbol( $version)]($style) "


      # ========================================================
      # DOCKER
      # ========================================================

      [docker_context]

      symbol = ""

      style = "bold cyan"

      format = "[$symbol( $context)]($style) "


      # ========================================================
      # TIME
      # ========================================================

      [time]

      disabled = true

      time_format = "%R"

      style = "bold muted"

      format = "[󰥔 $time]($style) "


      # ========================================================
      # COMMAND DURATION
      # ========================================================

      [cmd_duration]

      min_time = 1000

      style = "bold muted"

      format = "󰔟 [$duration]($style) "


      # ========================================================
      # PROMPT CHARACTER
      # ========================================================

      [character]

      success_symbol = "[➜](bold purple)"

      error_symbol = "[➜](bold red)"

      vimcmd_symbol = "[➜](bold cyan)"

      vimcmd_replace_one_symbol = "[➜](bold pink)"

      vimcmd_replace_symbol = "[➜](bold pink)"

      vimcmd_visual_symbol = "[➜](bold purple)"
    '';

  # GENERATE LUA FILES

  luaThemeFiles = lib.genAttrs themeNames (themeId: {
    text = themeToLua themeId;
  });

  # GENERATE JSON FILES

  jsonThemeFiles = lib.genAttrs themeNames (themeId: {
    text = themeToJson themeId;
  });

  # GENERATE KITTY FILES

  kittyThemeFiles = lib.genAttrs themeNames (themeId: {
    text = themeToKitty themeId;
  });

  # GENERATE STARSHIP FILES

  starshipThemeFiles = lib.genAttrs themeNames (themeId: {
    text = themeToStarship themeId;
  });

  # THEME LIST

  themeList = builtins.concatStringsSep "\n" (
    map (
      themeId:
      let
        theme = themeData.themes.${themeId};
      in
      "${themeId}\t${theme.name}"
    ) themeNames
  );

  # HOME MANAGER GENERATED FILES

  generatedLuaFiles = lib.mapAttrs' (
    themeId: file: lib.nameValuePair "aurora/themes/${themeId}.lua" file
  ) luaThemeFiles;

  generatedJsonFiles = lib.mapAttrs' (
    themeId: file: lib.nameValuePair "aurora/themes/${themeId}.json" file
  ) jsonThemeFiles;

  generatedKittyFiles = lib.mapAttrs' (
    themeId: file: lib.nameValuePair "aurora/themes/${themeId}.kitty.conf" file
  ) kittyThemeFiles;

  generatedStarshipFiles = lib.mapAttrs' (
    themeId: file: lib.nameValuePair "aurora/themes/${themeId}.starship.toml" file
  ) starshipThemeFiles;

in
{
  # STYLIX DESKTOP INTEGRATION

  stylix.targets.gtk.enable = true;

  stylix.targets.qt.enable = true;

  stylix.targets.fontconfig.enable = true;

  # GENERATED AURORA THEME DATABASE

  xdg.configFile = {
    # Complete Aurora database

    "aurora/themes.json".text = builtins.toJSON themeData;

    # Theme list, read by the Quickshell colorscheme picker

    "aurora/themes.list".text = themeList + "\n";

  }

  // generatedLuaFiles
  // generatedJsonFiles
  // generatedKittyFiles
  // generatedStarshipFiles;

  # RUNTIME THEME INITIALIZATION

  home.activation.initializeAuroraTheme = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    theme_dir="$HOME/.config/aurora"

    theme_file="$theme_dir/active-theme"

    active_lua="$theme_dir/active-theme.lua"

    active_kitty="$theme_dir/active-kitty.conf"


    active_starship="$theme_dir/active-starship.toml"


    mkdir -p "$theme_dir"


    # ========================================================
    # Create Default Theme
    # ========================================================

    if [ ! -f "$theme_file" ]; then

      printf '%s\n' "aurora" > "$theme_file"

    fi


    # ========================================================
    # Read Selected Theme
    # ========================================================

    selected="$(cat "$theme_file")"


    # ========================================================
    # Validate Selected Theme
    # ========================================================

    if [[ ! -f "$theme_dir/themes/$selected.lua" ]]; then

      printf '%s\n' "aurora" > "$theme_file"

      selected="aurora"

    fi


    # ========================================================
    # Active Lua Theme
    # ========================================================

    ln -sfn \
      "$theme_dir/themes/$selected.lua" \
      "$active_lua"


    # ========================================================
    # Active Kitty Theme
    # ========================================================

    if [[ -f "$theme_dir/themes/$selected.kitty.conf" ]]; then

      ln -sfn \
        "$theme_dir/themes/$selected.kitty.conf" \
        "$active_kitty"

    else

      ln -sfn \
        "$theme_dir/themes/aurora.kitty.conf" \
        "$active_kitty"

    fi


    # ========================================================
    # Active Starship Theme
    # ========================================================

    if [[ -f "$theme_dir/themes/$selected.starship.toml" ]]; then

      ln -sfn \
        "$theme_dir/themes/$selected.starship.toml" \
        "$active_starship"

    else

      ln -sfn \
        "$theme_dir/themes/aurora.starship.toml" \
        "$active_starship"

    fi
  '';

  # AURORA THEME SWITCHER

  home.file.".local/bin/aurora-theme" = {
    executable = true;

    text = ''
      #!/usr/bin/env bash

      set -euo pipefail


      # ========================================================
      # Paths
      # ========================================================

      CONFIG_DIR="$HOME/.config/aurora"

      THEMES_FILE="$CONFIG_DIR/themes.list"

      ACTIVE_THEME="$CONFIG_DIR/active-theme"

      ACTIVE_LUA="$CONFIG_DIR/active-theme.lua"

      ACTIVE_KITTY="$CONFIG_DIR/active-kitty.conf"

      ACTIVE_STARSHIP="$CONFIG_DIR/active-starship.toml"

      THEME_DIR="$CONFIG_DIR/themes"


      # ========================================================
      # Verify Aurora
      # ========================================================

      if [[ ! -f "$THEMES_FILE" ]]; then

        echo "Aurora: theme list not found." >&2

        exit 1

      fi


      # ========================================================
      # Select Theme
      # ========================================================

      if [[ $# -gt 0 ]]; then

        selected="$1"

      else

        echo "Aurora: usage: aurora-theme <theme-id|display-name>" >&2

        echo "Aurora: for a picker, run: qs ipc call theme toggle" >&2

        exit 1

      fi


      # ========================================================
      # User Cancelled
      # ========================================================

      [[ -z "$selected" ]] && exit 0


      # ========================================================
      # Resolve Display Name -> Theme ID
      # ========================================================

      theme_id="$(
        awk -F '\t' -v sel="$selected" '
          $1 == sel || $2 == sel {
            print $1
            exit
          }
        ' "$THEMES_FILE"
      )"


      # ========================================================
      # Validate Theme
      # ========================================================

      if [[ -z "$theme_id" ]]; then

        echo "Aurora: unknown theme: $selected" >&2

        exit 1

      fi


      # ========================================================
      # Theme Files
      # ========================================================

      theme_lua="$THEME_DIR/$theme_id.lua"

      theme_json="$THEME_DIR/$theme_id.json"

      theme_kitty="$THEME_DIR/$theme_id.kitty.conf"

      theme_starship="$THEME_DIR/$theme_id.starship.toml"


      # ========================================================
      # Verify Lua Theme
      # ========================================================

      if [[ ! -f "$theme_lua" ]]; then

        echo \
          "Aurora: generated Lua theme not found: $theme_id" \
          >&2

        exit 1

      fi


      # ========================================================
      # Verify JSON Theme
      # ========================================================

      if [[ ! -f "$theme_json" ]]; then

        echo \
          "Aurora: generated JSON theme not found: $theme_id" \
          >&2

        exit 1

      fi


      # ========================================================
      # Verify Kitty Theme
      # ========================================================

      if [[ ! -f "$theme_kitty" ]]; then

        echo \
          "Aurora: generated Kitty theme not found: $theme_id" \
          >&2

        exit 1

      fi


      # ========================================================
      # Verify Starship Theme
      # ========================================================

      if [[ ! -f "$theme_starship" ]]; then

        echo \
          "Aurora: generated Starship theme not found: $theme_id" \
          >&2

        exit 1

      fi


      # ========================================================
      # Update Active Theme
      # ========================================================

      printf '%s\n' "$theme_id" > "$ACTIVE_THEME"


      # ========================================================
      # Update Active Lua Theme
      # ========================================================

      ln -sfn \
        "$theme_lua" \
        "$ACTIVE_LUA"


      # ========================================================
      # Update Active Kitty Theme
      # ========================================================

      ln -sfn \
        "$theme_kitty" \
        "$ACTIVE_KITTY"


      # ========================================================
      # Update Active Starship Theme
      # ========================================================

      ln -sfn \
        "$theme_starship" \
        "$ACTIVE_STARSHIP"


      # ========================================================
      # Reload Hyprland
      # ========================================================

      if command -v hyprctl >/dev/null 2>&1; then

        hyprctl reload \
          >/dev/null 2>&1 || true

      fi


      # ========================================================
      # Reload Running Kitty Instances
      # ========================================================
      #
      # Kitty instances expose individual Unix sockets.
      #
      # Aurora discovers all active Kitty sockets and applies
      # the selected color palette to every running instance.
      #
      # ========================================================

      if command -v kitten >/dev/null 2>&1; then

        shopt -s nullglob


        kitty_sockets=(
          "$XDG_RUNTIME_DIR"/kitty-*
        )


        for socket in "''${kitty_sockets[@]}"; do

          # ----------------------------------------------------
          # Ignore non-socket files
          # ----------------------------------------------------

          [[ -S "$socket" ]] || continue


          # ----------------------------------------------------
          # Apply Aurora colors
          # ----------------------------------------------------

          kitten @ \
            --to "unix:$socket" \
            set-colors \
            --all \
            --configured \
            "$theme_kitty" \
            >/dev/null 2>&1 || true

        done

      fi

      # ========================================================
      # Refresh Running Zsh Sessions
      # ========================================================
      #
      # Notify all running interactive Zsh sessions through
      # their private ZLE refresh FIFO.
      #
      # ========================================================

      AURORA_ZSH_REFRESH_DIR="''${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/aurora-zsh"

      if [[ -d "$AURORA_ZSH_REFRESH_DIR" ]]; then

        for fifo in "$AURORA_ZSH_REFRESH_DIR"/*; do

          [[ -p "$fifo" ]] || continue
          (
          printf '%s\n' "refresh" > "$fifo"
          ) >/dev/null 2>&1 &

        done

      fi

      # ========================================================
      # Result
      # ========================================================

      echo "Aurora theme: $selected"
    '';
  };
}
