{ config, pkgs, ... }:

let
  colors = config.lib.stylix.colors;

  stylixColorsLua = ''
    -- ==========================================
    -- Stylix Generated Colors
    -- DO NOT EDIT
    -- Generated by Home Manager / Nix
    -- ==========================================

    return {
      base00 = "${colors.base00}",
      base01 = "${colors.base01}",
      base02 = "${colors.base02}",
      base03 = "${colors.base03}",
      base04 = "${colors.base04}",
      base05 = "${colors.base05}",
      base06 = "${colors.base06}",
      base07 = "${colors.base07}",
      base08 = "${colors.base08}",
      base09 = "${colors.base09}",
      base0A = "${colors.base0A}",
      base0B = "${colors.base0B}",
      base0C = "${colors.base0C}",
      base0D = "${colors.base0D}",
      base0E = "${colors.base0E}",
      base0F = "${colors.base0F}",

      withHashtag = {
        base00 = "#${colors.base00}",
        base01 = "#${colors.base01}",
        base02 = "#${colors.base02}",
        base03 = "#${colors.base03}",
        base04 = "#${colors.base04}",
        base05 = "#${colors.base05}",
        base06 = "#${colors.base06}",
        base07 = "#${colors.base07}",
        base08 = "#${colors.base08}",
        base09 = "#${colors.base09}",
        base0A = "#${colors.base0A}",
        base0B = "#${colors.base0B}",
        base0C = "#${colors.base0C}",
        base0D = "#${colors.base0D}",
        base0E = "#${colors.base0E}",
        base0F = "#${colors.base0F}",
      },
    }
  '';
in
{

  # ==========================================
  # Polkit Qt Environment Override
  # ==========================================

  xdg.configFile."systemd/user/plasma-polkit-agent.service.d/environment.conf".text = ''
    [Service]
    Environment=QT_STYLE_OVERRIDE=
  '';
  # ==========================================
  # Hyprland Lua Configuration
  # ==========================================

  xdg.configFile."hypr/hyprland.lua".source = ./hyprland.lua;

  xdg.configFile."hypr/config".source = ./config;

  # ==========================================
  # Stylix Colors
  # ==========================================

  xdg.configFile."hypr/stylix-colors.lua".text = stylixColorsLua;

  # ==========================================
  # Wallust Configuration
  # ==========================================

  xdg.configFile."wallust/wallust.toml".source = ./wallust/wallust.toml;

  xdg.configFile."wallust/templates/colors.lua".source = ./wallust/templates/colors.lua;

  xdg.configFile."wallust/templates/kitty.conf".source = ./wallust/templates/kitty.conf;

  xdg.configFile."wallust/templates/starship.toml".source = ./wallust/templates/starship.toml;

  xdg.configFile."wallust/templates/fuzzel.ini".source = ./wallust/templates/fuzzel.ini;

  # ==========================================
  # Wallpaper Scripts
  # ==========================================

  xdg.configFile."hypr/scripts/wallpaper.sh".source = ./scripts/wallpaper.sh;

  xdg.configFile."hypr/scripts/restore-wallpaper.sh".source = ./scripts/restore-wallpaper.sh;

  xdg.configFile."hypr/scripts/launcher.sh".source = ./scripts/launcher.sh;

  # ==========================================
  # Awww Wallpaper Daemon
  # ==========================================

  systemd.user.targets.desktop-services = {
    Unit = {
      Description = "Aurora desktop services";

      Wants = [
        "quickshell.service"
        "awww-daemon.service"
        "plasma-polkit-agent.service"
      ];
    };
  };

  systemd.user.services.quickshell = {
    Unit = {
      Description = "Quickshell desktop shell";
      PartOf = [ "desktop-services.target" ];
    };

    Service = {
      ExecStart = "${pkgs.quickshell}/bin/qs";
      Restart = "on-failure";
      RestartSec = 2;
    };
  };

  systemd.user.services.awww-daemon = {
    Unit = {
      Description = "Awww Wayland wallpaper daemon";
      PartOf = [ "desktop-services.target" ];
    };

    Service = {
      ExecStart = "${pkgs.awww}/bin/awww-daemon";
      Restart = "on-failure";
      RestartSec = 2;
    };
  };
}
